version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - ENV=mongo_dev

  mongodb:
    build:
      context: .
      dockerfile: Dockerfile_mongo
    ports:
      - "27017:27017"